- board: corne_min_right
    shield: rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_min_right_for_prospector
  - board: corne_min_left
    shield: settings_reset
    artifact-name: corne_min_settings_reset
